#ifndef __HTTP_STATUS_CODE_H__
#define __HTTP_STATUS_CODE_H__

enum class HTTPStatusCode {
    OK = 200,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    TEMPORARY_REDIRECT = 307,
    INTERNAL_SERVER_ERROR = 500
};

#endif
